### PR TITLE
Update 3.9

### PR DESCRIPTION
**Pull request by Arishamays1**
## ☆flit-core 3.9 Upload ☆
[Jira Ticket](https://anaconda.atlassian.net/browse/PKG-5338)

# Changes
-Added testing for `pip`
- Added recent dependencies for `run` section.

### CODE REVIEW

**Comment by Jrice1317** [comment]
Are we no longer using [this](https://github.com/AnacondaRecipes/flit-feedstock)?
￼

**Comment by lorepirri** [comment]
@Arishamays1 It seems that we have `flit-core` on defaults already with version `3.9.0` ( https://anaconda.org/anaconda/flit-core ).

It is probably coming from the multi-output recipe https://github.com/AnacondaRecipes/flit-feedstock/blob/master/recipe/meta.yaml as pointed out by @Jrice1317 .

Is this a rebuild? Is there a ticket with more information?

**Comment by Arishamays1** [comment]
@Jrice1317  @lorepirri  Thank you all for the quick response! You two are absolutely right! Great catch! Cloudpickle's most recent update to 3.0  required a new dependency specifying  `flit_core 3.9`. After utilizing `flit-core` instead, these works! Closing this PR now.

**Comment by lorepirri** [comment]
> @Jrice1317 @lorepirri Thank you all for the quick response! You two are absolutely right! Great catch! Cloudpickle's most recent update to 3.0 required a new dependency specifying `flit_core 3.9`. After utilizing `flit-core` instead, these works! Closing this PR now.

glad that this helped :)

**Comment by JeanChristopheMorinPerso** [comment]
I'll close this for now since I don't think it's required.

**Pull request closed without merging**
